// Mocks generated by Mockito 5.4.6 from annotations
// in aegis/test/presentation/viewmodels/blacklist_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:aegis/data/repositories/blacklist_repository.dart' as _i5;
import 'package:installed_apps/installed_apps.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:package_info_plus/package_info_plus.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [InstalledApps].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstalledApps extends _i1.Mock implements _i2.InstalledApps {
  MockInstalledApps() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [PackageInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackageInfo extends _i1.Mock implements _i3.PackageInfo {
  MockPackageInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get appName => (super.noSuchMethod(
        Invocation.getter(#appName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#appName),
        ),
      ) as String);

  @override
  String get packageName => (super.noSuchMethod(
        Invocation.getter(#packageName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#packageName),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  String get buildNumber => (super.noSuchMethod(
        Invocation.getter(#buildNumber),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#buildNumber),
        ),
      ) as String);

  @override
  String get buildSignature => (super.noSuchMethod(
        Invocation.getter(#buildSignature),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#buildSignature),
        ),
      ) as String);

  @override
  Map<String, dynamic> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [BlacklistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlacklistRepository extends _i1.Mock
    implements _i5.BlacklistRepository {
  MockBlacklistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<String>> getBlacklistedPackages() => (super.noSuchMethod(
        Invocation.method(
          #getBlacklistedPackages,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Stream<List<String>> watchBlacklistedPackages() => (super.noSuchMethod(
        Invocation.method(
          #watchBlacklistedPackages,
          [],
        ),
        returnValue: _i6.Stream<List<String>>.empty(),
      ) as _i6.Stream<List<String>>);

  @override
  _i6.Future<int> addAppToBlacklist(
    String? packageName,
    String? appName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAppToBlacklist,
          [
            packageName,
            appName,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> removeAppFromBlacklist(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAppFromBlacklist,
          [packageName],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
}
