// Mocks generated by Mockito 5.4.6 from annotations
// in aegis/test/presentation/viewmodels/calendar_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:aegis/core/services/notification_service.dart' as _i3;
import 'package:aegis/core/utils/notification_id_manager.dart' as _i4;
import 'package:aegis/data/local/database/app_database.dart' as _i6;
import 'package:aegis/data/repositories/events_repository.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamController_0<T> extends _i1.SmartFake
    implements _i2.StreamController<T> {
  _FakeStreamController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i3.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StreamController<String?> get selectNotificationStream =>
      (super.noSuchMethod(
        Invocation.getter(#selectNotificationStream),
        returnValue: _FakeStreamController_0<String?>(
          this,
          Invocation.getter(#selectNotificationStream),
        ),
      ) as _i2.StreamController<String?>);

  @override
  _i2.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> scheduleNotification({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? scheduledDate,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #scheduledDate: scheduledDate,
            #payload: payload,
          },
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> showImmediateNotification(
    String? title,
    String? body, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showImmediateNotification,
          [
            title,
            body,
          ],
          {#payload: payload},
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}

/// A class which mocks [NotificationIdManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationIdManager extends _i1.Mock
    implements _i4.NotificationIdManager {
  MockNotificationIdManager() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [EventsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventsRepository extends _i1.Mock implements _i5.EventsRepository {
  MockEventsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Stream<List<_i6.Event>> watchAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #watchAllEvents,
          [],
        ),
        returnValue: _i2.Stream<List<_i6.Event>>.empty(),
      ) as _i2.Stream<List<_i6.Event>>);

  @override
  _i2.Future<List<_i6.Event>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i2.Future<List<_i6.Event>>.value(<_i6.Event>[]),
      ) as _i2.Future<List<_i6.Event>>);

  @override
  _i2.Future<int> addEvent(
    String? title,
    bool? isAllDay,
    DateTime? date,
    DateTime? notificationAt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [
            title,
            isAllDay,
            date,
            notificationAt,
          ],
        ),
        returnValue: _i2.Future<int>.value(0),
      ) as _i2.Future<int>);

  @override
  _i2.Future<bool> updateEvent(_i6.Event? updatedEvent) => (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [updatedEvent],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<int> deleteEvent(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [id],
        ),
        returnValue: _i2.Future<int>.value(0),
      ) as _i2.Future<int>);
}
