// Mocks generated by Mockito 5.4.6 from annotations
// in aegis/test/presentation/viewmodels/habits_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aegis/data/local/database/app_database.dart' as _i4;
import 'package:aegis/data/repositories/habits_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HabitsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitsRepository extends _i1.Mock implements _i2.HabitsRepository {
  MockHabitsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Habit>> getAllHabits() => (super.noSuchMethod(
        Invocation.method(
          #getAllHabits,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Habit>>.value(<_i4.Habit>[]),
      ) as _i3.Future<List<_i4.Habit>>);

  @override
  _i3.Stream<List<_i4.Habit>> watchAllHabits() => (super.noSuchMethod(
        Invocation.method(
          #watchAllHabits,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Habit>>.empty(),
      ) as _i3.Stream<List<_i4.Habit>>);

  @override
  _i3.Future<List<_i4.HabitEntry>> getAllHabitEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllHabitEntries,
          [],
        ),
        returnValue: _i3.Future<List<_i4.HabitEntry>>.value(<_i4.HabitEntry>[]),
      ) as _i3.Future<List<_i4.HabitEntry>>);

  @override
  _i3.Stream<List<_i4.HabitEntry>> watchAllHabitEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllHabitEntries,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.HabitEntry>>.empty(),
      ) as _i3.Stream<List<_i4.HabitEntry>>);

  @override
  _i3.Future<List<_i4.HabitEntry>> getHabitEntriesByHabitId(int? habitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHabitEntriesByHabitId,
          [habitId],
        ),
        returnValue: _i3.Future<List<_i4.HabitEntry>>.value(<_i4.HabitEntry>[]),
      ) as _i3.Future<List<_i4.HabitEntry>>);

  @override
  _i3.Future<int> insertHabit(String? name) => (super.noSuchMethod(
        Invocation.method(
          #insertHabit,
          [name],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateHabit(
    int? id,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHabit,
          [
            id,
            newName,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteHabit(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> toggleHabitEntry(
    int? habitId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleHabitEntry,
          [
            habitId,
            date,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
