// Mocks generated by Mockito 5.4.6 from annotations
// in aegis/test/presentation/viewmodels/settings_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aegis/data/local/database/app_database.dart' as _i4;
import 'package:aegis/data/repositories/sessions_repository.dart' as _i5;
import 'package:aegis/data/repositories/settings_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Setting?> watchSettings() => (super.noSuchMethod(
        Invocation.method(
          #watchSettings,
          [],
        ),
        returnValue: _i3.Stream<_i4.Setting?>.empty(),
      ) as _i3.Stream<_i4.Setting?>);

  @override
  _i3.Future<_i4.Setting?> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _i3.Future<_i4.Setting?>.value(),
      ) as _i3.Future<_i4.Setting?>);

  @override
  _i3.Future<void> upsertSettings(_i4.SettingsCompanion? companion) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertSettings,
          [companion],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> deleteSettings() => (super.noSuchMethod(
        Invocation.method(
          #deleteSettings,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteAllData() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i5.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertSession(_i4.FocusSessionsCompanion? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSession,
          [session],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.FocusSession>> getLast30FocusSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLast30FocusSessions,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.FocusSession>>.value(<_i4.FocusSession>[]),
      ) as _i3.Future<List<_i4.FocusSession>>);

  @override
  _i3.Future<void> deleteAllSessions() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllSessions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
